import { createSlice } from "@reduxjs/toolkit";

const employee = [
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NJ",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2023",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "120 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",

    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2023",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "120 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",

    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2023",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "120 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "Washington",
    state: "NY",
    zipCode: "10001",

    department: "IT",
  },
  {
    firstName: "John",
    lastName: "Doe",
    birthDate: "01/01/1990",
    startDate: "01/01/2020",
    streetAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "IT",
  },
];

export const employeeSlice = createSlice({
  name: "employee",

  initialState: {
    employee,
  },

  reducers: {
    setEmployee: (state, action) => {
      state.employee.push(action.payload);
    },
  },
});

// export des actions
export const { setEmployee } = employeeSlice.actions;

export const selectEmployee = (state) => state.employee.employee;

export default employeeSlice.reducer;


